# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44210fe7b1c207203f6241a147db286d3f78312d02a657a667ec39037c5047a8151837b841a231f7aac4ef30eb499b51d324272698378a55782e24567a1cebb0

test:
  secret_key_base: 4733ce0fe6c8d4ec2b476094588681598033f185cdcb5bb39ca692e843e3178980f25811fae690d3bae9fa027904350b33f512938da475661543033ab01f2e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
